---
- name: configure iptables
  hosts: prod_app_servers:dev_app_servers
  vars_files:
    - vars/vars.configure-iptables.yml
  tasks:

  - name: check iptables exists
    become: yes
    apt:
      package: iptables
      state: present

  - name: temporary accept all chains traffic
    become: yes
    iptables:
      table: filter
      chain: '{{ item }}'
      policy: ACCEPT
    loop: ['INPUT', 'OUTPUT', 'FORWARD']

  - name: flush filter
    become: yes
    iptables:
      table: filter
      chain: '{{ item }}'
      flush: yes
    loop: ['INPUT', 'OUTPUT', 'FORWARD']

  - name: established/related
    become: yes
    iptables:
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT

  - name: allow loopback traffic
    become: yes
    iptables:
      table: filter
      chain: INPUT
      in_interface: lo
      jump: ACCEPT

  - name: allow ssh, tcp dns
    become: yes
    iptables:
      chain: INPUT
      protocol: tcp
      destination_ports:
      - '22'
      - '53'
      jump: ACCEPT

  - name: allow udp dns
    become: yes
    iptables:
      chain: INPUT
      protocol: udp
      destination_port: '53'
      jump: ACCEPT

  - name: allow dhcp offer and acknowledge
    become: yes
    iptables:
      chain: INPUT
      protocol: udp
      source_port: '67'
      destination_port: '68'
      jump: ACCEPT

  - name: allow icmp echo requests
    become: yes
    iptables:
      chain: INPUT
      protocol: icmp
      icmp_type: '8'
      jump: ACCEPT

  - name: allow web apps traffic
    become: yes
    iptables:
      chain: INPUT
      protocol: tcp
      destination_ports: '{{ APP_PORT_RANGE }}'
      jump: ACCEPT

  - name: allow extended services traffic
    become: yes
    iptables:
      chain: INPUT
      protocol: tcp
      destination_ports: '{{ EXTENDED_PORT_RANGE }}'
      jump: ACCEPT

  - name: default DORWARD and INPUT drop
    become: yes
    iptables:
      chain: '{{ item }}'
      policy: DROP
    loop: ['INPUT', 'FORWARD']
