---
- name: install environment
  hosts: prod_app_servers:dev_app_servers
  vars_files:
    - vars/vars.configure-environment.yml
  tasks:

  - name: install linux dependencies
    become: yes
    apt:
      pkg:
      - acl
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - git
      - build-essential
      - python3-pip
      update_cache: yes

  - name: stop apache
    become: yes
    service:
      name: apache2
      state: stopped

  - name:
    become: yes
    apt:
      name: apache2
      state: absent

  - name: install docker repo key
    become: yes
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: add docker repo
    become: yes
    shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    args:
      executable: /bin/bash

  - name: install docker
    become: yes
    apt:
      name: docker-ce
      state: latest
      update_cache: yes

  - name: add users to docker group
    become: yes
    user:
      name: "{{ item }}"
      state: present
      group: docker
    loop: "{{ DOCKER_USERS }}"

  - name: download docker-compose binary
    become: yes
    uri:
      url: "https://github.com/docker/compose/releases/download/v{{ COMPOSE_VERSION }}/docker-compose-Linux-x86_64"
      dest: /usr/local/bin/docker-compose
      status_code: [200, 304]

  - name: set docker-compose permissions
    become: yes
    file:
      path: /usr/local/bin/docker-compose
      mode: '755'
